/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.PL.Admin;

import Server.BL.Administrator;
import Server.BL.Coupon;
import Server.BL.IadminController;
import java.util.Vector;

/**
 *
 * @author Guy
 */
public class aproveCouponWindow extends javax.swing.JFrame {
    private Administrator admin;
    private javax.swing.JFrame back;
    private IadminController adminController;
    private Vector<Coupon> couponVec;
    public aproveCouponWindow(IadminController adminController,Administrator admin,javax.swing.JFrame back) {
        this.back=back;
        back.setVisible(false);
        this.admin=admin;
        this.adminController=adminController;
        couponVec=adminController.getUnaprovedCoupon();
        initComponents();
        this.setVisible(true);
    }
    /**
     * Creates new form aproveCouponWindow
     */
    private aproveCouponWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titlejLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        couponNamejComboBox = new javax.swing.JComboBox();
        deadlinejLabel1 = new javax.swing.JLabel();
        discountjLable1 = new javax.swing.JLabel();
        pricejLabel1 = new javax.swing.JLabel();
        descriptionjLabel1 = new javax.swing.JLabel();
        deadlinejLabel = new javax.swing.JLabel();
        discountjLable = new javax.swing.JLabel();
        pricejLabel = new javax.swing.JLabel();
        descriptionjLabel = new javax.swing.JLabel();
        namejLabel = new javax.swing.JLabel();
        businessjLabel1 = new javax.swing.JLabel();
        aprovejButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        logojLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        titlejLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titlejLabel.setText("aprove coupon");

        jLabel1.setText("business:");

        String [] coupons=new String[couponVec.size()];
        if(couponVec!=null&&couponVec.size()>0){
            for(int i=0;i<coupons.length;i++){
                coupons[i]=couponVec.elementAt(i).getName();
            }
        }
        couponNamejComboBox.setModel(new javax.swing.DefaultComboBoxModel(coupons));
        couponNamejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couponNamejComboBoxActionPerformed(evt);
            }
        });

        deadlinejLabel1.setText("           ");

        discountjLable1.setText("           ");

        pricejLabel1.setText("           ");

        descriptionjLabel1.setText("           ");

        deadlinejLabel.setText("deadline date:");

        discountjLable.setText("discount price:");

        pricejLabel.setText("price:");

        descriptionjLabel.setText("description:");

        namejLabel.setText("name:");

        businessjLabel1.setText("         ");

        aprovejButton.setText("aprove");
        aprovejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aprovejButtonActionPerformed(evt);
            }
        });

        backjButton.setText("back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        logojLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/PL/Images/logoSmall.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namejLabel)
                    .addComponent(descriptionjLabel)
                    .addComponent(pricejLabel)
                    .addComponent(discountjLable)
                    .addComponent(deadlinejLabel)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(couponNamejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(businessjLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deadlinejLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addComponent(discountjLable1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pricejLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backjButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(titlejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aprovejButton)))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titlejLabel)
                    .addComponent(aprovejButton))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namejLabel)
                            .addComponent(couponNamejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descriptionjLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(descriptionjLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pricejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discountjLable1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deadlinejLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pricejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discountjLable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deadlinejLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(businessjLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(backjButton)
                        .addContainerGap())
                    .addComponent(logojLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void couponNamejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couponNamejComboBoxActionPerformed
        Coupon c1=couponVec.elementAt(couponNamejComboBox.getSelectedIndex());
        discountjLable1.setText(c1.getDiscountPrice());
        descriptionjLabel1.setText(c1.getDescription());
        pricejLabel1.setText(c1.getPrice());
        deadlinejLabel1.setText(c1.getDeadLine());
        businessjLabel1.setText(c1.getBusinessName());
        this.repaint();
    }//GEN-LAST:event_couponNamejComboBoxActionPerformed

    private void aprovejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aprovejButtonActionPerformed
        if(couponNamejComboBox.getSelectedIndex()>=0){
            adminController.aproveCoupon(couponVec.elementAt(couponNamejComboBox.getSelectedIndex()));
            couponVec=adminController.getUnaprovedCoupon();
            String [] coupons=new String[couponVec.size()];
            if(couponVec!=null&&couponVec.size()>0){
                for(int i=0;i<coupons.length;i++){
                    coupons[i]=couponVec.elementAt(i).getName();
                }
                couponNamejComboBox.setModel(new javax.swing.DefaultComboBoxModel(coupons));
            }
            else{
                back.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_aprovejButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aproveCouponWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aproveCouponWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aproveCouponWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aproveCouponWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aproveCouponWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aprovejButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel businessjLabel1;
    private javax.swing.JComboBox couponNamejComboBox;
    private javax.swing.JLabel deadlinejLabel;
    private javax.swing.JLabel deadlinejLabel1;
    private javax.swing.JLabel descriptionjLabel;
    private javax.swing.JLabel descriptionjLabel1;
    private javax.swing.JLabel discountjLable;
    private javax.swing.JLabel discountjLable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logojLabel;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JLabel pricejLabel;
    private javax.swing.JLabel pricejLabel1;
    private javax.swing.JLabel titlejLabel;
    // End of variables declaration//GEN-END:variables
}
