/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.PL.Admin;

import Server.BL.Administrator;
import Server.BL.Coupon;
import Server.BL.IadminController;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Guy
 */
public class editCouponWindow extends javax.swing.JFrame {
    private Administrator admin;
    private javax.swing.JFrame back;
    private IadminController adminController;
    private Coupon coupon;
    public editCouponWindow(IadminController adminController,Administrator admin,javax.swing.JFrame back) {
        this.back=back;
        back.setVisible(false);
        this.admin=admin;
        this.adminController=adminController;
        this.coupon=null;
        initComponents();
        this.setVisible(true);
    }
    /**
     * Creates new form deleteCouponWindow
     */
    private editCouponWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titlejLabel = new javax.swing.JLabel();
        codejLabel = new javax.swing.JLabel();
        codejTextField = new javax.swing.JTextField();
        namejLabel = new javax.swing.JLabel();
        descriptionjLabel = new javax.swing.JLabel();
        pricejLabel = new javax.swing.JLabel();
        discountjLable = new javax.swing.JLabel();
        deadlinejLabel = new javax.swing.JLabel();
        findjButton = new javax.swing.JButton();
        backjButton1 = new javax.swing.JButton();
        editjButton = new javax.swing.JButton();
        namejTextField = new javax.swing.JTextField();
        descriptionjTextField = new javax.swing.JTextField();
        NumberFormat format=NumberFormat.getInstance();
        NumberFormatter formatter= new NumberFormatter(format);
        formatter.setValueClass(Integer.class);
        formatter.setMinimum(0);
        formatter.setMaximum(Integer.MAX_VALUE);
        formatter.setCommitsOnValidEdit(true);
        pricejFormattedTextField = new javax.swing.JFormattedTextField(formatter);
        NumberFormat format2=NumberFormat.getInstance();
        NumberFormatter formatter2= new NumberFormatter(format2);
        formatter2.setValueClass(Integer.class);
        formatter2.setMinimum(0);
        formatter2.setMaximum(Integer.MAX_VALUE);
        formatter2.setCommitsOnValidEdit(true);
        discountjFormattedTextField = new javax.swing.JFormattedTextField(formatter2);
        deadlinejFormattedTextField = new javax.swing.JFormattedTextField(new SimpleDateFormat("dd-M-yyyy"));
        logojLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        titlejLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titlejLabel.setText("delete coupon");

        codejLabel.setText("coupon code:");

        codejTextField.setText("insert  code here");

        namejLabel.setText("name:");

        descriptionjLabel.setText("description:");

        pricejLabel.setText("price:");

        discountjLable.setText("discount price:");

        deadlinejLabel.setText("deadline date:");

        findjButton.setText("find");
        findjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findjButtonActionPerformed(evt);
            }
        });

        backjButton1.setText("back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        editjButton.setVisible(false);
        editjButton.setText("edit");
        editjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editjButtonActionPerformed(evt);
            }
        });

        namejTextField.setEditable(false);
        namejTextField.setText("                 ");

        deadlinejFormattedTextField.setEditable(false);
        descriptionjTextField.setText("                 ");
        descriptionjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionjTextFieldActionPerformed(evt);
            }
        });

        pricejFormattedTextField.setEditable(false);

        discountjFormattedTextField.setEditable(false);

        deadlinejFormattedTextField.setText("dd-M-yyyy");
        deadlinejFormattedTextField.setEditable(false);
        deadlinejFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deadlinejFormattedTextFieldActionPerformed(evt);
            }
        });

        logojLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/PL/Images/logoSmall.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlejLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(codejLabel)
                                .addGap(28, 28, 28)
                                .addComponent(codejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(namejLabel)
                                            .addComponent(descriptionjLabel)
                                            .addComponent(pricejLabel)
                                            .addComponent(deadlinejLabel))
                                        .addGap(11, 11, 11))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(discountjLable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(deadlinejFormattedTextField)
                                    .addComponent(pricejFormattedTextField)
                                    .addComponent(discountjFormattedTextField)
                                    .addComponent(descriptionjTextField)
                                    .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(findjButton)
                            .addComponent(editjButton))))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backjButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codejLabel)
                    .addComponent(codejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namejLabel)
                            .addComponent(editjButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descriptionjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pricejLabel)
                        .addGap(41, 41, 41)
                        .addComponent(deadlinejLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descriptionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pricejFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(discountjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(discountjLable))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deadlinejFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(logojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backjButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findjButtonActionPerformed

        coupon=adminController.getCoupon(codejTextField.getText());
        if(coupon!=null){
            namejTextField.setText(coupon.getName());
            descriptionjTextField.setText(coupon.getDescription());
            pricejFormattedTextField.setText(coupon.getPrice());
            discountjFormattedTextField.setText(coupon.getDiscountPrice());
            deadlinejFormattedTextField.setText(coupon.getDeadLine());
            editjButton.setVisible(true);
            codejTextField.setEditable(false);
            namejTextField.setEditable(true);
            descriptionjTextField.setEditable(true);
            pricejFormattedTextField.setEditable(true);
            discountjFormattedTextField.setEditable(true);
            deadlinejFormattedTextField.setEditable(true);
            this.repaint();
        }
        else
            editjButton.setVisible(false);
    }//GEN-LAST:event_findjButtonActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backjButton1ActionPerformed

    private void editjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editjButtonActionPerformed
       try{
            adminController.editCoupon(coupon,namejTextField.getText(),descriptionjTextField.getText(),
                   (Integer)(pricejFormattedTextField.getValue()),
                   (Integer)(discountjFormattedTextField.getValue()),
                   deadlinejFormattedTextField.getText());
           back.setVisible(true);
           this.dispose();
       }catch(Exception e){
           
       }
    }//GEN-LAST:event_editjButtonActionPerformed

    private void descriptionjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionjTextFieldActionPerformed

    private void deadlinejFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deadlinejFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deadlinejFormattedTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editCouponWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editCouponWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editCouponWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editCouponWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editCouponWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JLabel codejLabel;
    private javax.swing.JTextField codejTextField;
    private javax.swing.JFormattedTextField deadlinejFormattedTextField;
    private javax.swing.JLabel deadlinejLabel;
    private javax.swing.JLabel descriptionjLabel;
    private javax.swing.JTextField descriptionjTextField;
    private javax.swing.JFormattedTextField discountjFormattedTextField;
    private javax.swing.JLabel discountjLable;
    private javax.swing.JButton editjButton;
    private javax.swing.JButton findjButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logojLabel;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JFormattedTextField pricejFormattedTextField;
    private javax.swing.JLabel pricejLabel;
    private javax.swing.JLabel titlejLabel;
    // End of variables declaration//GEN-END:variables
}
