/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.PL.Owner;

import Server.BL.Business;
import Server.BL.BusinessCategory;
import Server.BL.IownerController;
import Server.BL.Owner;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Guy
 */
public class addCouponWindow extends javax.swing.JFrame {

    /**
     * Creates new form addCouponWindow
     */
    Owner owner;
    Business business;
    IownerController ownerController;
    private javax.swing.JFrame back;
    public addCouponWindow(Owner owner,Business business,IownerController ownerController,javax.swing.JFrame back) {
        this.back=back;
        back.setVisible(false);
        this.owner= owner;
        this.business= business;
        this.ownerController= ownerController;
        initComponents();
        this.setVisible(true);
    }
    private addCouponWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namejLabel = new javax.swing.JLabel();
        descriptionjLabel = new javax.swing.JLabel();
        categoryjLabel = new javax.swing.JLabel();
        pricejLabel = new javax.swing.JLabel();
        discountjLable = new javax.swing.JLabel();
        deadlinejLabel = new javax.swing.JLabel();
        codejLabel = new javax.swing.JLabel();
        codejTextField = new javax.swing.JTextField();
        deadlinejFormattedTextField = new javax.swing.JFormattedTextField(new SimpleDateFormat("dd-M-yyyy"));
        NumberFormat format2=NumberFormat.getInstance();
        NumberFormatter formatter2= new NumberFormatter(format2);
        formatter2.setValueClass(Integer.class);
        formatter2.setMinimum(0);
        formatter2.setMaximum(Integer.MAX_VALUE);
        formatter2.setCommitsOnValidEdit(true);
        discountjFormattedTextField = new javax.swing.JFormattedTextField(formatter2);
        NumberFormat format=NumberFormat.getInstance();
        NumberFormatter formatter= new NumberFormatter(format);
        formatter.setValueClass(Integer.class);
        formatter.setMinimum(0);
        formatter.setMaximum(Integer.MAX_VALUE);
        formatter.setCommitsOnValidEdit(true);
        pricejFormattedTextField = new javax.swing.JFormattedTextField(formatter);
        categoryjComboBox = new javax.swing.JComboBox();
        descriptionjTextField = new javax.swing.JTextField();
        namejTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        titlejLabel = new javax.swing.JLabel();
        logojLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        namejLabel.setText("name:");

        descriptionjLabel.setText("description:");

        categoryjLabel.setText("category:");

        pricejLabel.setText("price:");

        discountjLable.setText("discount price:");

        deadlinejLabel.setText("deadline date:");

        codejLabel.setText("code:");

        deadlinejFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deadlinejFormattedTextFieldActionPerformed(evt);
            }
        });

        categoryjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HOTEL_SPA", "SPORTS", "RESTAURANT", "MOVIE_THEATER","OTHER" }));

        descriptionjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionjTextFieldActionPerformed(evt);
            }
        });

        jButton1.setText("add coupon");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        backjButton.setText("back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        titlejLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titlejLabel.setText("Add Coupon");

        logojLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/PL/Images/logoSmall.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namejLabel)
                    .addComponent(descriptionjLabel)
                    .addComponent(categoryjLabel)
                    .addComponent(pricejLabel)
                    .addComponent(discountjLable)
                    .addComponent(deadlinejLabel)
                    .addComponent(codejLabel))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deadlinejFormattedTextField)
                    .addComponent(pricejFormattedTextField)
                    .addComponent(discountjFormattedTextField)
                    .addComponent(categoryjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descriptionjTextField)
                    .addComponent(namejTextField)
                    .addComponent(codejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlejLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(logojLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backjButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namejLabel)
                    .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descriptionjLabel)
                            .addComponent(descriptionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoryjLabel)
                            .addComponent(categoryjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pricejLabel)
                            .addComponent(pricejFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(discountjLable)
                            .addComponent(discountjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deadlinejLabel)
                            .addComponent(deadlinejFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codejLabel)
                            .addComponent(codejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logojLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backjButton)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descriptionjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionjTextFieldActionPerformed

    private void deadlinejFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deadlinejFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deadlinejFormattedTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            int category=categoryjComboBox.getSelectedIndex();
            BusinessCategory businessCategory=BusinessCategory.OTHER;
            if(category==0)
                            businessCategory=BusinessCategory.HOTEL_SPA;
                    else if(category==1)
                            businessCategory=BusinessCategory.SPORTS;
                    else if(category==2)
                            businessCategory=BusinessCategory.RESTAURANT;
                    else if(category==0)
                            businessCategory=BusinessCategory.MOVIE_THEATER;
            int discount=(Integer)(discountjFormattedTextField.getValue());
            int price=(Integer)(pricejFormattedTextField.getValue());
            ownerController.addNewCoupon(codejTextField.getText(), namejTextField.getText(),descriptionjTextField.getText()
                    ,businessCategory , price, discount
                    , deadlinejFormattedTextField.getText(), business.getName());
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCouponWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCouponWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCouponWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCouponWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addCouponWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JComboBox categoryjComboBox;
    private javax.swing.JLabel categoryjLabel;
    private javax.swing.JLabel codejLabel;
    private javax.swing.JTextField codejTextField;
    private javax.swing.JFormattedTextField deadlinejFormattedTextField;
    private javax.swing.JLabel deadlinejLabel;
    private javax.swing.JLabel descriptionjLabel;
    private javax.swing.JTextField descriptionjTextField;
    private javax.swing.JFormattedTextField discountjFormattedTextField;
    private javax.swing.JLabel discountjLable;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logojLabel1;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JFormattedTextField pricejFormattedTextField;
    private javax.swing.JLabel pricejLabel;
    private javax.swing.JLabel titlejLabel;
    // End of variables declaration//GEN-END:variables
}
