/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.PL.Owner;

import Server.BL.Business;
import Server.BL.IownerController;
import Server.BL.Owner;
import Client.BL.localOwnerControler;
import java.util.Vector;

/**
 *
 * @author Guy
 */
public class OwnerWindow extends javax.swing.JFrame {

    /**
     * Creates new form OwnerWindow
     */
    private Owner owner;
    private Vector<Business> businessesVec;
    private IownerController ownerController;
    private javax.swing.JFrame back;
    private OwnerWindow() {
        initComponents();
    }
    public OwnerWindow(Owner owner,javax.swing.JFrame back) {
        ownerController=new localOwnerControler();
        this.back=back;
        this.owner=owner;
        businessesVec=null;
        businessesVec=ownerController.myStores(owner.getUserName());

        /*businessesVec=new Vector<Business>();
        Business b1=new Business("name1", "address1", "city1", " category1","description1",owner);
        Business b2=new Business("name2", "address2", "city1", " category1","description1",owner);
        businessesVec.add(b1);
        businessesVec.add(b2);*/
        initComponents();
        this.setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BusinessjComboBox = new javax.swing.JComboBox();
        businessNamejLabel = new javax.swing.JLabel();
        choosejButton = new javax.swing.JButton();
        addressjLabel = new javax.swing.JLabel();
        cityjLabel = new javax.swing.JLabel();
        categoryjLabel = new javax.swing.JLabel();
        discriptionjLabel = new javax.swing.JLabel();
        dispAddressjLabel = new javax.swing.JLabel();
        dispCityjLabel = new javax.swing.JLabel();
        dispCategoryjLabel = new javax.swing.JLabel();
        dispDiscriptionjLable = new javax.swing.JLabel();
        backjButton = new javax.swing.JButton();
        logojLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        if(businessesVec!=null&&businessesVec.size()>0){
            String [] business=new String[businessesVec.size()];
            for(int i=0;i<business.length;i++){
                business[i]=businessesVec.elementAt(i).getName();
            }
            BusinessjComboBox.setModel(new javax.swing.DefaultComboBoxModel(business));
            BusinessjComboBox.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BusinessjComboBoxActionPerformed(evt);
                }
            });
            Business b1=businessesVec.elementAt(BusinessjComboBox.getSelectedIndex());
            dispAddressjLabel.setText(b1.getAddress());
            dispCityjLabel.setText(b1.getCity());
            dispCategoryjLabel.setText(b1.getCategory());
            dispDiscriptionjLable.setText(b1.getDescription());
            this.repaint();
        }

        businessNamejLabel.setText("Business Name:");

        choosejButton.setText("choose business");
        choosejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosejButtonActionPerformed(evt);
            }
        });

        addressjLabel.setText("Address:");

        cityjLabel.setText("City:");

        categoryjLabel.setText("Category:");

        discriptionjLabel.setText("Discription:");

        dispAddressjLabel.setText("           ");

        dispCityjLabel.setText("           ");

        dispCategoryjLabel.setText("           ");

        dispDiscriptionjLable.setText("           ");

        backjButton.setText("back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        logojLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/PL/Images/logoSmall.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(businessNamejLabel)
                            .addComponent(discriptionjLabel)
                            .addComponent(categoryjLabel)
                            .addComponent(cityjLabel)
                            .addComponent(addressjLabel)))
                    .addComponent(logojLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dispAddressjLabel)
                                    .addComponent(dispCityjLabel)
                                    .addComponent(dispCategoryjLabel)
                                    .addComponent(dispDiscriptionjLable))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backjButton)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(BusinessjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(choosejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BusinessjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(businessNamejLabel)
                    .addComponent(choosejButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressjLabel)
                    .addComponent(dispAddressjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityjLabel)
                    .addComponent(dispCityjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryjLabel)
                    .addComponent(dispCategoryjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(discriptionjLabel)
                    .addComponent(dispDiscriptionjLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(backjButton)
                        .addGap(24, 24, 24))
                    .addComponent(logojLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BusinessjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusinessjComboBoxActionPerformed
        Business b1=businessesVec.elementAt(BusinessjComboBox.getSelectedIndex());
        dispAddressjLabel.setText(b1.getAddress());
        dispCityjLabel.setText(b1.getCity());
        dispCategoryjLabel.setText(b1.getCategory());
        dispDiscriptionjLable.setText(b1.getDescription());
        this.repaint();
    }//GEN-LAST:event_BusinessjComboBoxActionPerformed

    private void choosejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosejButtonActionPerformed
        if(BusinessjComboBox.getSelectedIndex()>=0&&businessesVec!=null&&businessesVec.size()>0)
            new BusinessWindow(owner,businessesVec.elementAt(BusinessjComboBox.getSelectedIndex()),ownerController,this);
        
    }//GEN-LAST:event_choosejButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OwnerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OwnerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OwnerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OwnerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OwnerWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox BusinessjComboBox;
    private javax.swing.JLabel addressjLabel;
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel businessNamejLabel;
    private javax.swing.JLabel categoryjLabel;
    private javax.swing.JButton choosejButton;
    private javax.swing.JLabel cityjLabel;
    private javax.swing.JLabel discriptionjLabel;
    private javax.swing.JLabel dispAddressjLabel;
    private javax.swing.JLabel dispCategoryjLabel;
    private javax.swing.JLabel dispCityjLabel;
    private javax.swing.JLabel dispDiscriptionjLable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logojLabel1;
    // End of variables declaration//GEN-END:variables
}
