/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.PL.Consumer;

import Server.BL.Business;
import Server.BL.IconsumerController;
import Server.BL.User;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Guy
 */
public class AddSocialNetworkCouponWindow extends javax.swing.JFrame {
    private IconsumerController consumerController;
    private javax.swing.JFrame back;
    private User consumer;
    private Vector<Business> businessesVec;

    public AddSocialNetworkCouponWindow(User user,IconsumerController userController,javax.swing.JFrame back) {
        this.back=back;
        back.setVisible(false);
        this.consumerController=userController;
        this.consumer=user;
        businessesVec=consumerController.getAllbusiness();
        initComponents();
        //checkNotifications();
        this.setVisible(true);
    }
    /**
     * Creates new form addSocialNetworkCoupon
     */
    private AddSocialNetworkCouponWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titlejLabel = new javax.swing.JLabel();
        logojLabel = new javax.swing.JLabel();
        businessjComboBox = new javax.swing.JComboBox();
        businessjLabel = new javax.swing.JLabel();
        namejTextField = new javax.swing.JTextField();
        descriptionjTextField = new javax.swing.JTextField();
        NumberFormat format=NumberFormat.getInstance();
        NumberFormatter formatter= new NumberFormatter(format);
        formatter.setValueClass(Integer.class);
        formatter.setMinimum(0);
        formatter.setMaximum(Integer.MAX_VALUE);
        formatter.setCommitsOnValidEdit(true);
        pricejFormattedTextField = new javax.swing.JFormattedTextField(formatter);
        NumberFormat format2=NumberFormat.getInstance();
        NumberFormatter formatter2= new NumberFormatter(format2);
        formatter2.setValueClass(Integer.class);
        formatter2.setMinimum(0);
        formatter2.setMaximum(Integer.MAX_VALUE);
        formatter2.setCommitsOnValidEdit(true);
        discountjFormattedTextField = new javax.swing.JFormattedTextField(formatter2);
        deadlinejFormattedTextField = new javax.swing.JFormattedTextField(new SimpleDateFormat("dd-M-yyyy"));
        codejTextField = new javax.swing.JTextField();
        codejLabel = new javax.swing.JLabel();
        deadlinejLabel = new javax.swing.JLabel();
        discountjLable = new javax.swing.JLabel();
        pricejLabel = new javax.swing.JLabel();
        descriptionjLabel = new javax.swing.JLabel();
        namejLabel = new javax.swing.JLabel();
        addCouponjButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        titlejLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titlejLabel.setText("Add Social Network Coupon");

        logojLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/PL/Images/logoSmall.jpg"))); // NOI18N

        String [] business=new String[businessesVec.size()];
        if(businessesVec!=null&&businessesVec.size()>0){
            for(int i=0;i<business.length;i++){
                business[i]=businessesVec.elementAt(i).getName();
            }
        }
        businessjComboBox.setModel(new javax.swing.DefaultComboBoxModel(business));
        businessjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessjComboBoxActionPerformed(evt);
            }
        });

        businessjLabel.setText("Business:");

        descriptionjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionjTextFieldActionPerformed(evt);
            }
        });

        deadlinejFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deadlinejFormattedTextFieldActionPerformed(evt);
            }
        });

        codejLabel.setText("code:");

        deadlinejLabel.setText("deadline date:");

        discountjLable.setText("discount price:");

        pricejLabel.setText("price:");

        descriptionjLabel.setText("description:");

        namejLabel.setText("name:");

        addCouponjButton.setText("add coupon");
        addCouponjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCouponjButtonActionPerformed(evt);
            }
        });

        backjButton.setText("back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titlejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(businessjLabel)
                        .addGap(18, 18, 18)
                        .addComponent(businessjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(logojLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namejLabel)
                            .addComponent(descriptionjLabel)
                            .addComponent(pricejLabel)
                            .addComponent(discountjLable)
                            .addComponent(deadlinejLabel)
                            .addComponent(codejLabel))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(codejTextField)
                            .addComponent(namejTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionjTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pricejFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(discountjFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deadlinejFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCouponjButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backjButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCouponjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namejLabel)
                    .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descriptionjLabel)
                            .addComponent(descriptionjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pricejLabel)
                            .addComponent(pricejFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(discountjLable)
                            .addComponent(discountjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deadlinejLabel)
                            .addComponent(deadlinejFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codejLabel)
                            .addComponent(codejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(businessjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(businessjLabel))
                        .addGap(32, 32, 32)
                        .addComponent(logojLabel))
                    .addComponent(backjButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void businessjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessjComboBoxActionPerformed
        
    }//GEN-LAST:event_businessjComboBoxActionPerformed

    private void descriptionjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionjTextFieldActionPerformed

    private void deadlinejFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deadlinejFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deadlinejFormattedTextFieldActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backjButtonActionPerformed

    private void addCouponjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCouponjButtonActionPerformed
        try{
            if(businessjComboBox.getSelectedIndex()>=0){
                Business business=businessesVec.elementAt(businessjComboBox.getSelectedIndex());
                int price=(Integer)(pricejFormattedTextField.getValue());
                consumerController.addNewCoupon(codejTextField.getText(), 
                        namejTextField.getText(),
                        descriptionjTextField.getText(), price,
                        (Integer)(discountjFormattedTextField.getValue()), deadlinejFormattedTextField.getText(),
                        business);
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_addCouponjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSocialNetworkCouponWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSocialNetworkCouponWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSocialNetworkCouponWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSocialNetworkCouponWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSocialNetworkCouponWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCouponjButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JComboBox businessjComboBox;
    private javax.swing.JLabel businessjLabel;
    private javax.swing.JLabel codejLabel;
    private javax.swing.JTextField codejTextField;
    private javax.swing.JFormattedTextField deadlinejFormattedTextField;
    private javax.swing.JLabel deadlinejLabel;
    private javax.swing.JLabel descriptionjLabel;
    private javax.swing.JTextField descriptionjTextField;
    private javax.swing.JFormattedTextField discountjFormattedTextField;
    private javax.swing.JLabel discountjLable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logojLabel;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JFormattedTextField pricejFormattedTextField;
    private javax.swing.JLabel pricejLabel;
    private javax.swing.JLabel titlejLabel;
    // End of variables declaration//GEN-END:variables
}
