/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.PL.Consumer;
import Client.BL.localConsumerControl;
import Server.BL.Consumer;
import Server.BL.IconsumerController;
import Server.BL.User;

/**
 *
 * @author Guy
 */
public class ConsumerWindow extends javax.swing.JFrame {

    private Consumer consumer;
    private javax.swing.JFrame back;
    private IconsumerController consumerController;
    Notification notification;
    public ConsumerWindow(Consumer user,javax.swing.JFrame back) {
        this.back=back;
        back.setVisible(false);
        this.consumer=user;
        consumerController=new localConsumerControl(user.getUserName());
        initComponents();
        setVisible(true);
        notification=new Notification(consumerController,consumer);
        //Notification.checkNotifications();
    }
    /**
     * Creates new form UserWindow
     */
    private ConsumerWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titlejLabel = new javax.swing.JLabel();
        addSocialNetworkCouponjButton = new javax.swing.JButton();
        showOrdersjButton = new javax.swing.JButton();
        rateUsedCouponjButton = new javax.swing.JButton();
        searchBusinessjButton = new javax.swing.JButton();
        searchCouponByBusinessjButton = new javax.swing.JButton();
        searchCouponByCategoryjButton = new javax.swing.JButton();
        searchCouponByLocationjButton = new javax.swing.JButton();
        logojLabel = new javax.swing.JLabel();
        backjButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        titlejLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titlejLabel.setText("hello");

        addSocialNetworkCouponjButton.setText("add social network coupon");
        addSocialNetworkCouponjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSocialNetworkCouponjButtonActionPerformed(evt);
            }
        });

        showOrdersjButton.setText("show my orders");
        showOrdersjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOrdersjButtonActionPerformed(evt);
            }
        });

        rateUsedCouponjButton.setText("rate used coupons");
        rateUsedCouponjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateUsedCouponjButtonActionPerformed(evt);
            }
        });

        searchBusinessjButton.setText("search business");
        searchBusinessjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBusinessjButtonActionPerformed(evt);
            }
        });

        searchCouponByBusinessjButton.setText("search coupon by business");
        searchCouponByBusinessjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCouponByBusinessjButtonActionPerformed(evt);
            }
        });

        searchCouponByCategoryjButton.setText("search coupon by category");
        searchCouponByCategoryjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCouponByCategoryjButtonActionPerformed(evt);
            }
        });

        searchCouponByLocationjButton.setText("search coupon by location");
        searchCouponByLocationjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCouponByLocationjButtonActionPerformed(evt);
            }
        });

        logojLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/PL/Images/logoSmall.jpg"))); // NOI18N

        backjButton1.setText("back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(titlejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchCouponByCategoryjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchCouponByLocationjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchCouponByBusinessjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchBusinessjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rateUsedCouponjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showOrdersjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addSocialNetworkCouponjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(logojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backjButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addSocialNetworkCouponjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showOrdersjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rateUsedCouponjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBusinessjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchCouponByBusinessjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchCouponByCategoryjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchCouponByLocationjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(logojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backjButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSocialNetworkCouponjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSocialNetworkCouponjButtonActionPerformed
        new AddSocialNetworkCouponWindow(consumer, consumerController, this);
        notification.checkNotifications();
    }//GEN-LAST:event_addSocialNetworkCouponjButtonActionPerformed

    private void showOrdersjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOrdersjButtonActionPerformed
        new DisplayOrdersWindow(consumer, consumerController, this);
        notification.checkNotifications();
    }//GEN-LAST:event_showOrdersjButtonActionPerformed

    private void rateUsedCouponjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateUsedCouponjButtonActionPerformed
        new RateUsedCouponsWindow(consumer, consumerController, this);
        notification.checkNotifications();
    }//GEN-LAST:event_rateUsedCouponjButtonActionPerformed

    private void searchBusinessjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBusinessjButtonActionPerformed
        new SearchBusinessWindow(consumer, consumerController, this);
        notification.checkNotifications();
    }//GEN-LAST:event_searchBusinessjButtonActionPerformed

    private void searchCouponByBusinessjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCouponByBusinessjButtonActionPerformed
        new SearchCouponByBusinessWindow(consumer, consumerController, this);
        notification.checkNotifications();
    }//GEN-LAST:event_searchCouponByBusinessjButtonActionPerformed

    private void searchCouponByCategoryjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCouponByCategoryjButtonActionPerformed
        new SearchCouponByCategoryWindow(consumer, consumerController, this);
        notification.checkNotifications();
    }//GEN-LAST:event_searchCouponByCategoryjButtonActionPerformed

    private void searchCouponByLocationjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCouponByLocationjButtonActionPerformed
        new SearchCouponByLocationWindow(consumer, consumerController, this);
        notification.checkNotifications();
    }//GEN-LAST:event_searchCouponByLocationjButtonActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backjButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsumerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsumerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsumerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsumerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsumerWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSocialNetworkCouponjButton;
    private javax.swing.JButton backjButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logojLabel;
    private javax.swing.JButton rateUsedCouponjButton;
    private javax.swing.JButton searchBusinessjButton;
    private javax.swing.JButton searchCouponByBusinessjButton;
    private javax.swing.JButton searchCouponByCategoryjButton;
    private javax.swing.JButton searchCouponByLocationjButton;
    private javax.swing.JButton showOrdersjButton;
    private javax.swing.JLabel titlejLabel;
    // End of variables declaration//GEN-END:variables
}
