/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.PL.Consumer;

import Server.BL.ActiveCoupon;
import Server.BL.Coupon;
import Server.BL.IconsumerController;
import Server.BL.User;
import java.util.Vector;

/**
 *
 * @author Guy
 */
public class RateUsedCouponsWindow extends javax.swing.JFrame {
    private IconsumerController consumerController;
    private javax.swing.JFrame back;
    private User user;
    Vector<ActiveCoupon> activeCouponVec;
    public RateUsedCouponsWindow(User user,IconsumerController userController,javax.swing.JFrame back) {
        this.back=back;
        back.setVisible(false);
        this.consumerController=userController;
        this.user=user;
        activeCouponVec=consumerController.getUnratedUsedCoupons(user.getUserName());
        initComponents();
        //checkNotifications();
        this.setVisible(true);
    }
    /**
     * Creates new form rateUsedCoupons
     */
    private RateUsedCouponsWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titlejLabel = new javax.swing.JLabel();
        couponsjComboBox = new javax.swing.JComboBox();
        serialNumberjLabel = new javax.swing.JLabel();
        serialNumberjLabel1 = new javax.swing.JLabel();
        descriptionjLabel = new javax.swing.JLabel();
        categoryjLabel = new javax.swing.JLabel();
        pricejLabel = new javax.swing.JLabel();
        discountPricejLabel = new javax.swing.JLabel();
        deadlinejLabel = new javax.swing.JLabel();
        deadlinejLabel1 = new javax.swing.JLabel();
        discountjLable1 = new javax.swing.JLabel();
        pricejLabel1 = new javax.swing.JLabel();
        categoryjLabel1 = new javax.swing.JLabel();
        descriptionjLabel1 = new javax.swing.JLabel();
        ratejLabel = new javax.swing.JLabel();
        ratejButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        logojLabel = new javax.swing.JLabel();
        ratejComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        titlejLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titlejLabel.setText("rate used coupons");

        String [] coupons=new String[activeCouponVec.size()];
        if(activeCouponVec!=null&&activeCouponVec.size()>0){
            for(int i=0;i<coupons.length;i++){
                coupons[i]=activeCouponVec.elementAt(i).getCoupon().getName()+","+activeCouponVec.elementAt(i).getSerialNumber();
            }
        }
        couponsjComboBox.setModel(new javax.swing.DefaultComboBoxModel(coupons));
        couponsjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couponsjComboBoxActionPerformed(evt);
            }
        });

        serialNumberjLabel.setText("Serial Number:");

        serialNumberjLabel1.setText("         ");

        descriptionjLabel.setVisible(false);
        descriptionjLabel.setText("Description:");

        categoryjLabel.setVisible(false);
        categoryjLabel.setText("Category:");

        pricejLabel.setVisible(false);
        pricejLabel.setText("Price:");

        discountPricejLabel.setVisible(false);
        discountPricejLabel.setText("Discount Price:");

        deadlinejLabel.setVisible(false);
        deadlinejLabel.setText("Deadline:");

        deadlinejLabel1.setText("           ");

        discountjLable1.setText("           ");

        pricejLabel1.setText("           ");

        categoryjLabel1.setText("           ");

        descriptionjLabel1.setText("           ");

        ratejLabel.setText("Rate:");

        ratejButton.setText("rate!");
        ratejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratejButtonActionPerformed(evt);
            }
        });

        backjButton.setText("back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        logojLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/PL/Images/logoSmall.jpg"))); // NOI18N

        ratejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4","5" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(serialNumberjLabel)
                                .addGap(18, 18, 18)
                                .addComponent(serialNumberjLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(descriptionjLabel)
                                        .addComponent(categoryjLabel)
                                        .addComponent(pricejLabel)
                                        .addComponent(discountPricejLabel)
                                        .addComponent(deadlinejLabel)
                                        .addComponent(ratejLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(logojLabel))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(deadlinejLabel1)
                                            .addComponent(descriptionjLabel1)
                                            .addComponent(categoryjLabel1)
                                            .addComponent(pricejLabel1)
                                            .addComponent(discountjLable1)
                                            .addComponent(ratejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(140, 140, 140))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(backjButton)))))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(couponsjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ratejButton)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(titlejLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(couponsjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratejButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialNumberjLabel)
                    .addComponent(serialNumberjLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionjLabel)
                    .addComponent(descriptionjLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryjLabel)
                    .addComponent(categoryjLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pricejLabel)
                    .addComponent(pricejLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discountPricejLabel)
                    .addComponent(discountjLable1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deadlinejLabel)
                    .addComponent(deadlinejLabel1))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backjButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ratejLabel)
                            .addComponent(ratejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logojLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void couponsjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couponsjComboBoxActionPerformed
        Coupon c=activeCouponVec.get(couponsjComboBox.getSelectedIndex()).getCoupon();
        descriptionjLabel1.setText(c.getDescription());
        discountjLable1.setText(c.getDiscountPrice());
        deadlinejLabel1.setText(c.getDeadLine());
        pricejLabel1.setText(c.getPrice());
        categoryjLabel1.setText(c.getCategory());
        serialNumberjLabel1.setText(activeCouponVec.get(couponsjComboBox.getSelectedIndex()).getSerialNumber());
    }//GEN-LAST:event_couponsjComboBoxActionPerformed

    private void ratejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratejButtonActionPerformed
        if(couponsjComboBox.getSelectedIndex()>=0){
            int rate=ratejComboBox.getSelectedIndex()+1;
            int serial=Integer.parseInt(activeCouponVec.get(couponsjComboBox.getSelectedIndex()).getSerialNumber());
            consumerController.rateActiveCoupon(serial,activeCouponVec.get(couponsjComboBox.getSelectedIndex()).getCoupon().getCode(),rate);



            activeCouponVec=consumerController.getUnratedUsedCoupons(user.getUserName());
            String [] coupons=new String[activeCouponVec.size()];
            if(activeCouponVec!=null&&activeCouponVec.size()>0){
                for(int i=0;i<coupons.length;i++){
                    coupons[i]=activeCouponVec.elementAt(i).getCoupon().getName()+","+activeCouponVec.elementAt(i).getSerialNumber();
                }
                couponsjComboBox.setModel(new javax.swing.DefaultComboBoxModel(coupons));

                Coupon c=activeCouponVec.get(couponsjComboBox.getSelectedIndex()).getCoupon();
                descriptionjLabel1.setText(c.getDescription());
                discountjLable1.setText(c.getDiscountPrice());
                deadlinejLabel1.setText(c.getDeadLine());
                pricejLabel1.setText(c.getPrice());
                categoryjLabel1.setText(c.getCategory());
                serialNumberjLabel1.setText(activeCouponVec.get(couponsjComboBox.getSelectedIndex()).getSerialNumber());
            }
            else{
                back.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_ratejButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RateUsedCouponsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RateUsedCouponsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RateUsedCouponsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RateUsedCouponsWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RateUsedCouponsWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel categoryjLabel;
    private javax.swing.JLabel categoryjLabel1;
    private javax.swing.JComboBox couponsjComboBox;
    private javax.swing.JLabel deadlinejLabel;
    private javax.swing.JLabel deadlinejLabel1;
    private javax.swing.JLabel descriptionjLabel;
    private javax.swing.JLabel descriptionjLabel1;
    private javax.swing.JLabel discountPricejLabel;
    private javax.swing.JLabel discountjLable1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logojLabel;
    private javax.swing.JLabel pricejLabel;
    private javax.swing.JLabel pricejLabel1;
    private javax.swing.JButton ratejButton;
    private javax.swing.JComboBox ratejComboBox;
    private javax.swing.JLabel ratejLabel;
    private javax.swing.JLabel serialNumberjLabel;
    private javax.swing.JLabel serialNumberjLabel1;
    private javax.swing.JLabel titlejLabel;
    // End of variables declaration//GEN-END:variables
}
