/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.PL.Consumer;

import Server.BL.Business;
import Server.BL.IconsumerController;
import Server.BL.User;
import java.util.Vector;

/**
 *
 * @author Guy
 */
public class SearchBusinessWindow extends javax.swing.JFrame {
    private IconsumerController consumerController;
    private javax.swing.JFrame back;
    private User user;
    Vector<Business> businessesVec;
    public SearchBusinessWindow(User user,IconsumerController consumerController,javax.swing.JFrame back) {
        this.back=back;
        back.setVisible(false);
        this.consumerController=consumerController;
        this.user=user;
        businessesVec=consumerController.getAllbusiness();
        initComponents();
        //checkNotifications();
        this.setVisible(true);
    }
    /**
     * Creates new form searchBusiness
     */
    private SearchBusinessWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        titlejLabel2 = new javax.swing.JLabel();
        businessNamejLabel2 = new javax.swing.JLabel();
        addressjLabel2 = new javax.swing.JLabel();
        cityjLabel2 = new javax.swing.JLabel();
        categoryjLabel2 = new javax.swing.JLabel();
        discriptionjLabel2 = new javax.swing.JLabel();
        BusinessjComboBox2 = new javax.swing.JComboBox();
        backjButton2 = new javax.swing.JButton();
        dispAddressjLabel2 = new javax.swing.JLabel();
        dispCityjLabel2 = new javax.swing.JLabel();
        dispCategoryjLabel2 = new javax.swing.JLabel();
        dispDiscriptionjLable2 = new javax.swing.JLabel();
        logojLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        titlejLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titlejLabel2.setText("Search Business");

        businessNamejLabel2.setText("Name,Owner:");

        addressjLabel2.setText("Address:");

        cityjLabel2.setText("City:");

        categoryjLabel2.setText("Category:");

        discriptionjLabel2.setText("Discription:");

        if(businessesVec!=null&&businessesVec.size()>0){
            String [] business=new String[businessesVec.size()];
            for(int i=0;i<business.length;i++){
                business[i]=businessesVec.elementAt(i).getName()+","+businessesVec.elementAt(i).getOwner().getUserName();
            }
            BusinessjComboBox2.setModel(new javax.swing.DefaultComboBoxModel(business));
            BusinessjComboBox2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    BusinessjComboBox2ActionPerformed(evt);
                }
            });
            Business b1=businessesVec.elementAt(BusinessjComboBox2.getSelectedIndex());
            dispAddressjLabel2.setText(b1.getAddress());
            dispCityjLabel2.setText(b1.getCity());
            dispCategoryjLabel2.setText(b1.getCategory());
            dispDiscriptionjLable2.setText(b1.getDescription());
            this.repaint();
        }

        backjButton2.setText("back");
        backjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton2ActionPerformed(evt);
            }
        });

        dispAddressjLabel2.setText("           ");

        dispCityjLabel2.setText("           ");

        dispCategoryjLabel2.setText("           ");

        dispDiscriptionjLable2.setText("           ");

        logojLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Client/PL/Images/logoSmall.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titlejLabel2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(businessNamejLabel2)
                                    .addComponent(discriptionjLabel2)
                                    .addComponent(categoryjLabel2)
                                    .addComponent(cityjLabel2)
                                    .addComponent(addressjLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BusinessjComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(dispDiscriptionjLable2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                        .addComponent(dispCategoryjLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dispCityjLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dispAddressjLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(logojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backjButton2)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlejLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BusinessjComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(businessNamejLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(addressjLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cityjLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoryjLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discriptionjLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(dispAddressjLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dispCityjLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dispCategoryjLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dispDiscriptionjLable2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logojLabel)
                    .addComponent(backjButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BusinessjComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusinessjComboBox2ActionPerformed
        Business b1=businessesVec.elementAt(BusinessjComboBox2.getSelectedIndex());
        dispAddressjLabel2.setText(b1.getAddress());
        dispCityjLabel2.setText(b1.getCity());
        dispCategoryjLabel2.setText(b1.getCategory());
        dispDiscriptionjLable2.setText(b1.getDescription());
        this.repaint();
    }//GEN-LAST:event_BusinessjComboBox2ActionPerformed

    private void backjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton2ActionPerformed
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backjButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchBusinessWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchBusinessWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchBusinessWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchBusinessWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchBusinessWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox BusinessjComboBox2;
    private javax.swing.JLabel addressjLabel2;
    private javax.swing.JButton backjButton2;
    private javax.swing.JLabel businessNamejLabel2;
    private javax.swing.JLabel categoryjLabel2;
    private javax.swing.JLabel cityjLabel2;
    private javax.swing.JLabel discriptionjLabel2;
    private javax.swing.JLabel dispAddressjLabel2;
    private javax.swing.JLabel dispCategoryjLabel2;
    private javax.swing.JLabel dispCityjLabel2;
    private javax.swing.JLabel dispDiscriptionjLable2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logojLabel;
    private javax.swing.JLabel titlejLabel2;
    // End of variables declaration//GEN-END:variables
}
